# Generated by Django 3.2.7 on 2021-09-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Djeca',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Muško'), (1, 'Žensko')], default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(default='-', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Koordinatori',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(default='-', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Institucije',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Muško'), (1, 'Žensko')], default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(default='-', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Volonteri',
            },
        ),
        migrations.CreateModel(
            name='VolunteerReport',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField()),
                ('satisfaction', models.IntegerField(blank=True, choices=[(0, ':('), (1, ':/'), (2, ':)')], null=True)),
                ('report', models.TextField(blank=True, max_length=1000, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevencija.child')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevencija.coordinator')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevencija.volunteer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
