# Generated by Django 3.2.7 on 2021-09-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevencija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='volunteer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prevencija.volunteer'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prevencija.department'),
        ),
    ]
