# Generated by Django 3.2.7 on 2021-09-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencija', '0003_auto_20210921_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Djece'},
        ),
    ]
