# Generated by Django 3.2.7 on 2021-09-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencija', '0004_alter_child_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Djeca'},
        ),
    ]
