# Generated by Django 3.2.7 on 2021-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencija', '0006_auto_20210922_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'DODIJELJEN'), (0, 'NIJE DODIJELJEN')], default=1),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'AKTIVAN'), (0, 'NEAKTIVAN')], default=1),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'AKTIVAN'), (0, 'NEAKTIVAN')], default=1),
        ),
    ]
