# Generated by Django 3.2.7 on 2021-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencija', '0007_auto_20210922_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'U PROGRAMU'), (0, 'NIJE U PROGRAMU')], default=1),
        ),
    ]
